name: text_to_voice
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: ^3.7.0
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    flutter_tts: ^4.2.2
    translator: ^1.0.3+1
    permission_handler: ^11.4.0
    flutter_sound: ^9.28.0
    connectivity_plus: ^6.1.3
    flutter_riverpod: ^2.6.1
    uuid: ^4.5.1
    record: ^6.0.0
    file_picker: ^10.0.0
    share_plus: ^10.1.4
    speech_to_text: ^7.0.0
    flutter_animate: ^4.5.2
    google_fonts: ^6.2.1
    dart_openai: ^5.1.0
    flutter_dotenv: ^5.2.1
    flutter_chat_types: ^3.6.2
    flutter_chat_ui: ^1.6.15
    flutter_bloc: ^9.1.0
    loading_animation_widget: ^1.3.0
    
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
flutter:
    uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages